const POLYGON_CHAIN = 137;
const MUMBAI_CHAIN = 80001;
const RINKEBY_CHAIN = 4;
const AURORA_CHAIN = 1313161555;
module.exports = {
    POLYGON_CHAIN,
    MUMBAI_CHAIN,
    RINKEBY_CHAIN,
    AURORA_CHAIN
}